spring:

  application:
    name: tlias-web-management

  datasource:
    url: jdbc:mysql://localhost:3306/db01
    username: root
    password: 555371
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper_locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启驼峰命名映射开关
    map-underscore-to-camel-case: true