spring:

  application:
    name: tlias-web-management

  datasource:
    url: jdbc:mysql://localhost:3306/db01
    username: root
    password: 555371
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      # 一次性可以上传多个文件
      max-request-size: 100MB
      # 单个文件的大小
      max-file-size: 10MB


mybatis:
  mapper_locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启驼峰命名映射开关
    map-underscore-to-camel-case: true

logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug

